version: 2

sources:
  - name: northwind_bq
    description: "northwind dw big query"
    database: valid-sol-346522
    schema: northwind
    tables:
      - name: public_categories
      - name: public_customers
      - name: public_employees
      - name: public_order_details
      - name: public_orders
      - name: public_products
      - name: public_region
      - name: public_shippers
      - name: public_suppliers
      - name: public_territories



  # - name: northwind
  #   description: "northwind database"
  #   database: northwind
  #   schema: public
  #   tables:
  #     - name: categories
  #     - name: customer_customer_demo
  #     - name: customer_demographics
  #     - name: customers
  #     - name: employee_territories
  #     - name: employees
  #     - name: order_details
  #     - name: oeders
  #     - name: products
  #     - name: region
  #     - name: shippers
  #     - name: supliers
  #     - name: territories
  #     - name: us_states